name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 0.4.1
repository: https://github.com/fluttercommunity/flutter_google_places

environment:
  sdk: '>=3.2.3'
  flutter: '>=3.16.4'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: any
  google_maps_webservice: any
  http: any
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
